# Generated by Django 4.2 on 2023-05-05 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0002_category_animals_cat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animals",
            options={
                "ordering": ["time_create", "title"],
                "verbose_name": "Необычные животные",
                "verbose_name_plural": "Необычные животные",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterField(
            model_name="animals",
            name="cat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="animals.category",
                verbose_name="Категории",
            ),
        ),
        migrations.AlterField(
            model_name="animals",
            name="content",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="animals",
            name="photo",
            field=models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Фото"),
        ),
        migrations.AlterField(
            model_name="animals",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время добавления"
            ),
        ),
        migrations.AlterField(
            model_name="animals",
            name="time_published",
            field=models.BooleanField(default=True, verbose_name="Публикация"),
        ),
        migrations.AlterField(
            model_name="animals",
            name="time_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
        ),
        migrations.AlterField(
            model_name="animals",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Категория"
            ),
        ),
    ]
